In [4]:
import pandas as pd
import numpy as np

In [6]:
# 1.读取数据
path = "../../resource/cancer/breast-cancer-wisconsin.data"
column_name = ["Sample code number", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape",
               "Marginal Adhesion", "Single Epithelial Cell Size",
               "Bare Nuclei", "Bland Chromatin", "Normal Nucleoli", "Mitoses", "Class"]
data = pd.read_csv(path, names=column_name)

In [7]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [8]:
# 2.数据处理
# 1)替换-》np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2)删除缺失样本
data.dropna(inplace=True)

In [9]:
data.isnull().any()  # 说明不存在缺失值了

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [10]:
# 3)筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

In [11]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [12]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [20]:
# 4).划分数据集
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [14]:
# 3.特征工程 标准化
from sklearn.preprocessing import StandardScaler

In [15]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [16]:
x_train

array([[-0.12573845, -0.66103707, -0.71188293, ..., -0.16190324,
        -0.59288775, -0.33848482],
       [ 1.68263479,  0.33832606,  0.67927761, ...,  0.24644385,
         1.7524872 , -0.33848482],
       [-0.4874131 , -0.66103707, -0.71188293, ..., -0.57025033,
        -0.25783419, -0.33848482],
       ...,
       [-1.2107624 , -0.66103707, -0.71188293, ..., -0.97859742,
        -0.59288775, -0.33848482],
       [-1.2107624 , -0.66103707, -0.71188293, ..., -0.16190324,
        -0.59288775, -0.33848482],
       [-1.2107624 , -0.66103707, -0.71188293, ..., -0.97859742,
        -0.59288775, -0.33848482]])

In [17]:
x_test

array([[ 0.95928549,  0.6714471 ,  1.02706774, ...,  0.65479094,
         0.07721938, -0.33848482],
       [ 1.32096014,  0.33832606,  0.33148747, ..., -0.57025033,
         0.74732651,  0.28267729],
       [ 0.2359362 ,  1.67081023,  1.72264801, ...,  1.8798322 ,
         2.42259433,  0.90383939],
       ...,
       [-1.2107624 , -0.66103707, -0.71188293, ..., -0.57025033,
        -0.59288775, -0.33848482],
       [ 0.2359362 , -0.66103707, -0.01630266, ..., -0.97859742,
        -0.59288775, -0.33848482],
       [-0.4874131 , -0.66103707, -0.71188293, ..., -0.57025033,
        -0.59288775, -0.33848482]])

In [18]:
# 4 机器学习算法训练 - 模型
from sklearn.linear_model import LogisticRegression

In [19]:
# 1) 逻辑回归预估器
estimator = LogisticRegression()
estimator.fit(x_train, y_train)

LogisticRegression()

In [35]:
# 2)逻辑回归的模型参数 ：回归系数
estimator.coef_

array([[1.36138109, 0.99126667, 0.75422055, 0.71020172, 0.21070533,
        1.00476737, 1.02649748, 0.20188277, 0.426596  ]])

In [36]:
estimator.intercept_

array([-1.33967666])

In [38]:
# 5.模型评估
# 1）直接对比准确率
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("对比真实值和预测值\n", y_predict == y_test)

score = estimator.score(x_test, y_test)
print("准确率为:\n", score)

y_predict:
 [2 2 2 2 2 4 2 4 4 2 4 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 2 4 4 2 2 4 2 4 4 2 2
 4 4 4 4 4 4 2 2 2 2 4 2 4 2 2 4 2 4 2 4 2 2 4 2 2 4 2 4 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 2 2 2 4 4 2 4 2 4 4 4 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 4 4 2 2
 2 2 2 4 4 2 2 2 2 2 2 4 4 2 4 2 2 2 4 2 4 2 2 2 2 4 4 4 4 2 4 4 2 2 2 2 4
 2 4 2 4 2 2 4 4 2 4 4 2 2 4 4 4 2 2 2 4 4 2 4]
对比真实值和预测值
 480    True
651    True
676    True
597    True
392    True
       ... 
474    True
151    True
267    True
645    True
112    True
Name: Class, Length: 171, dtype: bool
准确率为:
 0.9590643274853801


In [39]:
# 2）查看精确率，召回率，f1-score
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict, labels=[
                               2, 4], target_names=["良性", "恶性"])
print(report)

              precision    recall  f1-score   support

          良性       0.95      0.98      0.97       100
          恶性       0.97      0.93      0.95        71

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171



In [45]:
#3) 使用ROC曲线 AUC指标评价 
# y_true 每个样本的真实类别，必须为0（反例），1（正）标记
# 将y_test装换成 0 1
y_true = np.where(y_test > 3, 1, 0)
print(y_true)
print(y_predict)

[0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 0
 1 1 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 0 1
 0 0 1 0 1 0 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1
 1 1 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1]
[2 2 2 2 2 4 2 4 4 2 4 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 2 4 4 2 2 4 2 4 4 2 2
 4 4 4 4 4 4 2 2 2 2 4 2 4 2 2 4 2 4 2 4 2 2 4 2 2 4 2 4 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 2 2 2 4 4 2 4 2 4 4 4 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 4 4 2 2
 2 2 2 4 4 2 2 2 2 2 2 4 4 2 4 2 2 2 4 2 4 2 2 2 2 4 4 4 4 2 4 4 2 2 2 2 4
 2 4 2 4 2 2 4 4 2 4 4 2 2 4 4 4 2 2 2 4 4 2 4]


In [44]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_true, y_predict)

0.9547887323943662